version: 2
updates:
  - package-ecosystem: npm
    directory: /xx7rg
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /api
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
